[[news]]
date = "2026-07"
content = "Joined Prof. Changhong Linghu's group at City University of Hong Kong as a Summer Research Assistant."

[[news]]
date = "2024-08"
content = "Joined Prof. Jizhou Song's research group at Zhejiang University as an Undergraduate Researcher."
